### ISSUE TITLE
Discussion for “Detecting causal relationships in distributed computations: in search of the holy grail”

### ISSUE THREAD

**Issue by git-ram** [lkuper/CSE232-2020-10#7]
@maxwellrbradley 
@ravina-gelda 
@meghnaburli 
@abhay3010 
@katelynstone13

**Comment by katelynstone13** [comment]
Me!

**Comment by git-ram** [comment]
Thanks! Just added you!

**Comment by lkuper** [comment]
Some quick feedback on the current state of the discussion summary:

* For Q1, "There were no preceding causal events" is confusing because it sounds like you're saying that there were no events preceding `e_33`.
* For Q2, how about some discussion of what these different notions of consistency mean (or what you think they mean)?  Right now it looks more or less like what I wrote down during class, but surely there were further notes that scribes took in your own groups.
* For Q3, I'm confused by a few things.  For "We believe that you only enforce strict causal ordering if it leads to correct execution of the program.", what does "correct" mean in this context?  Also, allowing concurrent operations to execute simultaneously, *is* something that can happen when you strictly enforce causal ordering, because if they're concurrent then they don't have a causal order.  Finally, "When a resource with only a single possible user is required by two processes that otherwise could execute concurrently (i.e. bank account)." is a sentence fragment.

**Comment by maxwellrbradley** [comment]
@lkuper the newest updates are now ready for you to look at on the wiki page. Thank you for the feedback! Please let us know if you have further comments and we would be happy to make the corresponding changes.

**Comment by meghnaburli** [comment]
@lkuper Thank you for the feedback. The updates for the second question are pending.We will update here once that is done.

**Comment by meghnaburli** [comment]
@lkuper All updates are complete. Please let us know if you have further comments.
